### ISSUE TITLE
cannot create listening socket [:::2375] after #108

### ISSUE THREAD

**Issue by jscheytt** [Tecnativa/docker-socket-proxy#109]
Hi there,

we are running docker-socket-proxy in Docker Swarm (docker engine v23). Since the newest nightly build, we get this error on startup:

```
[WARNING] 340/080535 (1) : config : missing timeouts for backend 'docker-events'.
   | While not properly invalid, you will certainly encounter various problems
   | with such a configuration. To fix this, please ensure that all following
   | timeouts are set to a non-zero value: 'client', 'connect', 'server'.
[WARNING] 340/080535 (1) : Can't open global server state file '/var/lib/haproxy/server-state': No such file or directory
Proxy dockerbackend started.
Proxy docker-events started.
[NOTICE] 340/080535 (1) : haproxy version is 2.2.31-d69335f
[ALERT] 340/080535 (1) : Starting frontend dockerfrontend: cannot create listening socket [:::2375]
```

This is likely related to https://github.com/Tecnativa/docker-socket-proxy/pull/108.

We have not set up any IPv6 configuration in the Docker daemon nor in our networks. Do we need to do that in order for docker-socket-proxy to keep working?

This is roughly how we deploy docker-socket-proxy in Docker Swarm currently:

```yaml
version: "3.9"
services:
  docker-socket-proxy:
    deploy:
      mode: global
      update_config:
        order: start-first
      resources:
        limits:
          memory: "104857600"
          pids: 1000
        reservations:
          cpus: "0.02"
          memory: "104857600"
      restart_policy:
        condition: on-failure
        max_attempts: 5
      placement:
        constraints:
        - node.role == manager
    environment:
      CONTAINERS: "1"
      NETWORKS: "1"
      NODES: "1"
      POST: "1"
      SERVICES: "1"
      SWARM: "1"
      TASKS: "1"
    healthcheck:
      test:
      - CMD-SHELL
      - wget -O - http://127.0.0.1:2375/_ping
      interval: 5s
      retries: 10
    image: tecnativa/docker-socket-proxy:nightly@sha256:46148a17aad9df1c21e4b7f173b8c0b5efe213ab90b193cec583d5adcaa16965
    logging:
      options:
        tag: '{{.Name}}'
    networks:
      internal: null
    volumes:
    - type: bind
      source: /var/run/docker.sock
      target: /var/run/docker.sock
      read_only: true
networks:
  internal: {}
```
