### ISSUE TITLE
restrict to network/docker-compose services

### ISSUE THREAD

**Issue by Scarbous** [Tecnativa/docker-socket-proxy#11]
Hi, is it posible that I can only access (throug docker.sock) information of containers/services which are in an spesific network, or better only containers/services which I defined in my docker-compose?

My goal is to host multiple Systems, every System has a docker-compose.yml and I want to use a traefik container in every docker-compose System.

**Comment by Yajo** [comment]
Sadly not with this image. You should try some advanced permission system such as https://www.openpolicyagent.org/.

I use this configuration for traefik and it is enough for it to work:

```yaml
    dockersocket:
        image: tecnativa/docker-socket-proxy
        privileged: true
        networks:
            private:
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        environment:
            CONTAINERS: 1
            NETWORKS: 1
            SERVICES: 1
            SWARM: 1
            TASKS: 1
        restart: unless-stopped
```
