### ISSUE TITLE
Error starting user land proxy: listen tcp4 127.0.0.1:2375: bind: address already in use

### ISSUE THREAD

**Issue by crazyelectron-io** [Tecnativa/docker-socket-proxy#143]
I run docker-socket-proxy alongside Homepage but somehow the proxy refuses to start because the bind address is already in use.
```
Error response from daemon: driver failed programming external connectivity on endpoint dockerproxy (0412ec4ffda68af87f84323b217a6b9b5d02f3dee5a14c41bb2fb882918e55e8): failed to bind port 127.0.0.1:2375/tcp: Error starting userland proxy: listen tcp4 127.0.0.1:2375: bind: address already in use
```
The docker compose code is:
```yaml
  dockerproxy:
    image: ghcr.io/tecnativa/docker-socket-proxy:latest
    container_name: dockerproxy
    environment:
      - CONTAINERS=1 # Allow access to viewing containers
      - SERVICES=1 # Allow access to viewing services (necessary when using Docker Swarm)
      - TASKS=1 # Allow access to viewing tasks (necessary when using Docker Swarm)
      - POST=0 # Disallow any POST operations (effectively read-only)
    ports:
      - 127.0.0.1:2375:2375
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped
```
The `netstat` output shows no process bound to that address:
```shell
tcp        0      0 0.0.0.0:8080            0.0.0.0:*               LISTEN      -
tcp        0      0 0.0.0.0:8008            0.0.0.0:*               LISTEN      -
tcp        0      0 0.0.0.0:443             0.0.0.0:*               LISTEN      -
tcp        0      0 0.0.0.0:80              0.0.0.0:*               LISTEN      -
tcp        0      0 0.0.0.0:111             0.0.0.0:*               LISTEN      -
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      -
tcp        0      0 0.0.0.0:8443            0.0.0.0:*               LISTEN      -
tcp        0      0 127.0.0.1:34491         0.0.0.0:*               LISTEN      383633/code-33fc5a9
tcp        0      0 172.18.0.1:49956        172.18.0.9:9696         ESTABLISHED -
tcp        0      0 10.0.0.6:9696           172.18.0.7:35190        ESTABLISHED -
tcp        0      0 10.0.0.6:8989           172.18.0.12:36456       ESTABLISHED -
tcp        0      0 10.0.0.6:8008           172.18.0.2:37090        TIME_WAIT   -
tcp        0      0 127.0.0.1:34491         127.0.0.1:54342         ESTABLISHED 383633/code-33fc5a9
tcp        0      0 127.0.0.1:54342         127.0.0.1:34491         ESTABLISHED -
tcp        0      0 10.0.0.6:37092          10.100.0.2:445          ESTABLISHED -
tcp        0      0 10.0.0.6:7878           172.18.0.12:57696       ESTABLISHED -
tcp        0      0 10.0.0.6:9696           172.18.0.7:35208        ESTABLISHED -
tcp        0      0 10.0.0.6:22             10.10.2.156:50823       ESTABLISHED -
tcp        0      0 172.18.0.1:49946        172.18.0.9:9696         ESTABLISHED -
tcp        0      0 172.18.0.1:49944        172.18.0.9:9696         ESTABLISHED -
tcp        0      0 10.0.0.6:9696           172.18.0.7:35198        ESTABLISHED -
tcp        0      0 10.0.0.6:9696           172.18.0.7:35220        ESTABLISHED -
tcp        0      0 172.18.0.1:41260        172.18.0.7:8989         ESTABLISHED -
tcp        0      0 172.18.0.1:49966        172.18.0.9:9696         ESTABLISHED -
tcp        0   3212 10.0.0.6:22             10.10.2.156:49950       ESTABLISHED -
tcp        0      0 172.18.0.1:49932        172.18.0.9:9696         ESTABLISHED -
tcp        0      0 10.0.0.6:8008           172.18.0.2:37088        TIME_WAIT   -
tcp        0      0 10.0.0.6:9696           172.18.0.7:35178        ESTABLISHED -
tcp        0      0 172.18.0.1:39962        172.18.0.2:7878         ESTABLISHED -
udp        0      0 0.0.0.0:111             0.0.0.0:*                           -
udp        0      0 0.0.0.0:7359            0.0.0.0:*
```
What could cause this? Also, I'm not sure to which network I should bind the container. I tried both a separate network and the same network as Homepage.
