### ISSUE TITLE
Is there an healthcheck entrypoint?

### ISSUE THREAD

**Issue by pascalandy** [Tecnativa/docker-socket-proxy#24]
As I plan to use this project along traefik in prod, an healthcheck is required. I would expect something to configure something like:

```
version: "3.3"

services:

  socketproxy:
    image: tecnativa/docker-socket-proxy
    container_name: socketproxy
    hostname: socketproxy
    restart: unless-stopped
    healthcheck:
      test: curl -fail http://localhost:8181/health || exit 1
      interval: 5s
      timeout: 2s
      retries: 3
      start_period: 5s
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      CONTAINERS: 1
```

**Comment by SuperSandro2000** [comment]
Can't you just request the ``/info`` endpoint and parse some docker specific response?

**Comment by Yajo** [comment]
I never faced this yet, so if you can open a PR on how to do that, either with fixes or at least with docs, I'll be glad to review and merge.

**Comment by pascalandy** [comment]
@SuperSandro2000 I'm not sure to understand the logic. There is nothing at /info

```
# RUN: docker-compose -f compose-socketproxy.yml up -d
version: "3.7"

services:

  socketproxy:
    image: tecnativa/docker-socket-proxy
    container_name: socketproxy
    hostname: socketproxy
    restart: unless-stopped
    healthcheck:
      disable: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      CONTAINERS: 1
```

What do you see when you start the container and go to: http://localhost/info ?

**Comment by pascalandy** [comment]
Me either but we never know :-p

> I never faced this yet

**Comment by Yajo** [comment]
Since the container is exposing a subset of the docker API, I guess @SuperSandro2000 means that you should just use that API and, if it responds, it means the proxy is doing its work.

**Comment by pascalandy** [comment]
I see your logic. 

But within the healthcheck context, I don't think the healthcheck function can access the docker's API (specially for this very container which is a proxy). That's why the healthcheck is using a classic ping to know if the container is alive or not.

```
    healthcheck:
      test: curl -fail http://localhost:8181/health || exit 1
      interval: 5s
      timeout: 2s
      retries: 3
      start_period: 5s
```

**Comment by Yajo** [comment]
> But within the healthcheck context, I don't think the healthcheck function can access the docker's API (specially for this very container which is a proxy).

Why?

**Comment by pascalandy** [comment]
> Why

The Healtcheck function exist because the Docker API cannot know if an APP is up or down. The test needs to happen within the container. When it fails, the the Docker API reboot the container.

**Comment by SuperSandro2000** [comment]
Just access the docker api trough the proxy. If that works the proxy works, if not the proxy does not work.

So that could work:
````
  healthcheck:
      test: curl -fail http://localhost:2375/v1.24/info || exit 1
````

**Comment by pascalandy** [comment]
I tried but the container does not start:

```
  socketproxy:
    image: tecnativa/docker-socket-proxy
    hostname: socketproxy
    networks:
      - ntw_proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      NETWORKS: 1
      SERVICES: 1
      TASKS: 1
      # SWARM: 1
      # CONTAINERS: 1
    deploy:
      update_config:
        order: start-first
      restart_policy:
        condition: any
        delay: 10s
        max_attempts: 50
      mode: global
      resources:
        limits:
          cpus: '0.20'
          memory: 8M
    healthcheck:
      test: curl -fail http://localhost:2375/v1.24/info || exit 1
      interval: "10s"
      timeout: "5s"
      retries: 5
      start_period: "40s"
```

**Comment by Yajo** [comment]
Are you running it on swarm? If so, make sure to run it in manager nodes.

**Comment by Ranbato** [comment]
I didn't see curl in the image so I'm doing the healthcheck with the following
 `    healthcheck:
      test: ["CMD", "wget", "http://localhost:2375/version"]
      interval: 29s
      timeout: 2s
      retries: 3
      start_period: 21s`
I use it to force the containers that depend on it to start up after it.

**Comment by SuperSandro2000** [comment]
You need to pass ``--spider`` to ``wget``.

**Comment by pascalandy** [comment]
I feel this makes sens now:

```
version: "3.7"

services:

  socketproxy:
    image: tecnativa/docker-socket-proxy
    container_name: socketproxy
    hostname: socketproxy
    restart: unless-stopped
    healthcheck:
      test: curl -fail http://localhost:2375/version || exit 1
      interval: "29s"
      timeout: "5s"
      retries: 3
      start_period: "21"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      CONTAINERS: 1

```
