### ISSUE TITLE
can't fetch service

### ISSUE THREAD

**Issue by oliverlj** [Tecnativa/docker-socket-proxy#27]
hello,
I have this stack on a swarm cluster :
```
services:
  dockerproxy:
    image: tecnativa/docker-socket-proxy
    privileged: true
    deploy:
      placement:
        constraints:
          - node.role == manager
    environment:
      CONTAINERS: 1
      NETWORKS: 1
      POST: 1
      SERVICES: 1
      SWARM: 1
      TASKS: 1
    networks:
      - docker-socket
    ports:
      - protocol: tcp
        published: 2375
        target: 2375
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
```

I can access containers: 
```
oliver@fz-manager-1:~$ docker container ls
CONTAINER ID        IMAGE                                  COMMAND                  CREATED             STATUS              PORTS               NAMES
9bfaabc7f264        tecnativa/docker-socket-proxy:latest   "/docker-entrypoint.…"   2 minutes ago       Up 2 minutes        2375/tcp            infra_dockerproxy.1.xwzozoorpy29wjgvk2fw04517
f957acd29b76        portainer/agent:latest                 "./agent"                21 hours ago        Up 21 hours                             infra_agent.cvq7fcrp5yym6k4cga6yhkwnj.ww7weeuft3epioahnr3wqjavm
```

but not services :
```
oliver@fz-manager-1:~$ docker service ls
Error response from daemon: <html><body><h1>403 Forbidden</h1>
Request forbidden by administrative rules.
</body></html>
```

Here is the docker version :
```
oliver@fz-manager-1:~$ docker version
Client:
 Version:           19.03.8
 API version:       1.40
 Go version:        go1.13.8
 Git commit:        afacb8b7f0
 Built:             Wed Mar 11 23:42:35 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          19.03.8
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.8
  Git commit:       afacb8b7f0
  Built:            Wed Mar 11 22:48:33 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.3.3-0ubuntu2
  GitCommit:        
 runc:
  Version:          spec: 1.0.1-dev
  GitCommit:        
 docker-init:
  Version:          0.18.0
  GitCommit:        
```
