### ISSUE TITLE
Performance degradation

### ISSUE THREAD

**Issue by mbelangergit** [Tecnativa/docker-socket-proxy#35]
Hi,

I’m trying to use your image on with my containers but I see a performance degradation compared to using `/var/run/docker.sock`. For example I'm using Dozzle, a Realtime log viewer for docker containers and if connected
with `DOCKER_HOST=tcp://...`, it's operation is very slow while using about 25 containers in my setup (home automation and "off-the-could" stuff, Home Assistant, Mosquitto, bitwarden_rs, Emby, etc.). I get the same performance drop from Traefik too, I'm using Dozzle here since it is easy to replicate the issue, no volumes, variables or complex settings.

I tried to debug this with a clean setup on a blank Debian VM with only 3 containers, docker-socket-proxy and two instances of Dozzle, one connected to `/var/run/docker.sock` and the other one to docker-socket-proxy. I can see the differences while accessing the services pages in my browser. Just by opening the 2 pages side by side and hit refresh in the browser. The instance connected to docker-socket-proxy will be refreshed much slowly than the other one. It is worst on my real system where it takes few seconds to refresh while it is almost instantly refreshed while connected to `/var/run/docker.sock`. It seems that more containers in the stack, slower the accesses to the Docker socket are.

Is a performance degradation is expected using docker-socket-proxy?

Here is my test docker-compose:

```
version: "3.8"

networks:
  socket_proxy:
    name: socket_proxy

services:
  socketproxy:
    container_name: socketproxy
    image: tecnativa/docker-socket-proxy:latest
    privileged: true
    environment:
      CONTAINERS: 1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - socket_proxy

  dozzle:
    container_name: dozzle
    image: amir20/dozzle:latest
    #environment:
    #  DOCKER_HOST: tcp://socketproxy:2375
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - socket_proxy
    ports:
      - 8080:8080/tcp
    depends_on:
      - socketproxy

  dozzle2:
    container_name: dozzle2
    image: amir20/dozzle:latest
    environment:
      DOCKER_HOST: tcp://socketproxy:2375
    #volumes:
    #  - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - socket_proxy
    ports:
      - 8081:8080/tcp
    depends_on:
      - socketproxy
```
Any ideas?

Thanks!
