### ISSUE TITLE
Docs on Swarm need to point out it must be deployed on manager nodes

### ISSUE THREAD

**Issue by dukejones** [Tecnativa/docker-socket-proxy#67]
In Docker Swarm, the docker socket only exists on manager nodes, so this was failing sporadically for me without much explanation until I realized it was whenever the proxy was deployed to a worker node. Here are the constraints required in docker compose format:

```yml
 deploy:
      mode: global
      placement:
        constraints:
          - node.role == manager
```
